id: P004441
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:22:01.625258
source_metadata:
  id: bdr:W293
  title: སྙན་ངག་གི་བསྟན་བཅོས་མེ་ལོང་གི་རྩ་བ་དང་འགྲེལ་པ་དབྱངས་ཅན་དགྱེས་པའི་གླུ་དབྱངས།
  author: ''
  volumes:
    b62bae04bc9141dc99cd989547316103:
      image_group_id: I1KG10667
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
