id: P004441
initial_creation_type: ocr
source_metadata:
  id: bdr:W293
  title: སྙན་ངག་གི་བསྟན་བཅོས་མེ་ལོང་གི་རྩ་བ་དང་འགྲེལ་པ་དབྱངས་ཅན་དགྱེས་པའི་གླུ་དབྱངས།
  author: ''
  volumes:
    b62bae04bc9141dc99cd989547316103:
      image_group_id: I1KG10667
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
